-- ===================================================================
-- BOOKME — SEED DATA SCRIPT (PostgreSQL / Supabase)
-- Version: 2.0 (Clean - No mock businesses or mock profiles)
-- Description: Intentionally blank. Tenants and profiles register dynamically.
-- ===================================================================
